---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by foyjog.
--- DateTime: 12/25/21 10:35 AM
---
-- As an example, the following grammar matches strings of a's and b's that have the same number of a's and b's:

local lpeg = require("lpeg")
local table2string = require("table2string")

equalcount = lpeg.Ct(lpeg.P{
    "S";   -- initial rule name
    S = "a" * lpeg.V"B" + "b" * lpeg.V"A" + "",
    A = "a" * lpeg.V"S" + "b" * lpeg.V"A" * lpeg.V"A",
    B = "b" * lpeg.V"S" + "a" * lpeg.V"B" * lpeg.V"B",
} * -1 / tostring)

print(table2string.tostring(equalcount:match("aabb")))