---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by foyjog.
--- DateTime: 12/25/21 11:03 AM
---
--- from https://leafo.net/guides/parsing-expression-grammars.html

local lpeg = require("lpeg")
local table2string = require("table2string")

local integer = lpeg.R("09")^1 / tonumber
local integer_or_char = integer + lpeg.P(1)
local extract_ints = lpeg.Ct(integer_or_char^0)

print(table2string.tostring(extract_ints:match("hello!"))) --> {}
print(table2string.tostring(extract_ints:match("hello 123"))) --> {123}
print(table2string.tostring(extract_ints:match("5 5 5 yeah 7 7 7 "))) --> {5,5,5,7,7,7}