---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by foyjog.
--- DateTime: 12/25/21 10:37 AM
---
-- From http://lua-users.org/wiki/TableUtils
--
local table2string = {}

function table2string.val_to_str ( v )
    if "string" == type( v ) then
        v = string.gsub( v, "\n", "\\n" )
        if string.match( string.gsub(v,"[^'\"]",""), '^"+$' ) then
            return "'" .. v .. "'"
        end
        return '"' .. string.gsub(v,'"', '\\"' ) .. '"'
    else
        return "table" == type( v ) and table2string.tostring( v ) or
                tostring( v )
    end
end

function table2string.key_to_str ( k )
    if "string" == type( k ) and string.match( k, "^[_%a][_%a%d]*$" ) then
        return k
    else
        return "[" .. table2string.val_to_str( k ) .. "]"
    end
end

--From https://github.com/falcosecurity/falco/blob/master/userspace/engine/lua/rule_loader.lua
function table2string.tostring( tbl )
    local result, done = {}, {}
    for k, v in ipairs( tbl ) do
        table.insert( result, table2string.val_to_str( v ) )
        done[ k ] = true
    end
    for k, v in pairs( tbl ) do
        if not done[ k ] then
            table.insert( result,
                    table2string.key_to_str( k ) .. "=" .. table2string.val_to_str( v ) )
        end
    end
    return "{" .. table.concat( result, "," ) .. "}"
end



return table2string